name: Build TWRP for VGOTEL Note 23

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the TWRP repository
      uses: actions/checkout@v4

    - name: Set up build environment and sync sources
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y git python3-pip

        # Install repo tool
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        export PATH=~/bin:$PATH

        # Init and sync TWRP source
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1 --depth=1
        repo sync -j$(nproc --all)

        # Add device tree manifest
        mkdir -p .repo/local_manifests
        echo '<manifest><project name="vader113/twrp_note23" path="device/ssh/NOTE_23" remote="github" revision="main" /></manifest>' > .repo/local_manifests/device_ssh_NOTE_23.xml
        repo sync -j$(nproc --all)
      shell: bash

    - name: Set up environment and build TWRP
      run: |
        source build/envsetup.sh
        lunch twrp_NOTE_23-eng
        make recoveryimage -j$(nproc --all)
      shell: bash

    - name: Upload TWRP recovery image
      uses: actions/upload-artifact@v4
      with:
        name: recovery-image
        path: out/target/product/NOTE_23/recovery.img

    - name: Clean up
      run: |
        rm -rf out/
